spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://app_user:app_password@mongodb:27017/fitness_recommendation?authSource=admin
      database: fitness_recommendation

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8080/eureka/
