spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fitness
    username: app_user
    password: app_password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8080/eureka/