spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://postgres:5432/fitness
    username: app_user
    password: app_password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8080/eureka/